RevenueControl/RevenueControl.Web/Models/TransactionsViewModel.cs
using System.Collections.Generic;
using RevenueControl.DomainObjects.Entities;

namespace RevenueControl.Web.Models
{
    public class TransactionsViewModel
    {
        public int DataSourceId { get; set; }

        public string DataSource { get; set; }

        public IEnumerable<Transaction> Transactions { get; set; }
    }
}

RevenueControl/RevenueControl.Web/Controllers/TransactionUploadController.cs
using System.IO;
using System.Web.Mvc;
using RevenueControl.DataAccess;
using RevenueControl.DomainObjects.Interfaces;
using RevenueControl.InquiryFileReaders.Csv;
using RevenueControl.Services;

namespace RevenueControl.Web.Controllers
{
    [Authorize]
    public class TransactionUploadController : BaseController
    {
        private readonly IDataSourceManager _dataSourceManager = new DataSourceManager(new UnitOfWork());

        private readonly ITransactionManager _transactionManager = new TransactionsManager(new UnitOfWork(),
            new GenericCsvReader());


        // GET: TransactionUpload
        public ActionResult Index([Bind(Prefix = "id")] int dataSourceId)
        {
            ViewData["Id"] = dataSourceId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload([Bind(Prefix = "id")] int dataSourceId)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if ((file != null) && (file.ContentLength > 0))
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/UploadedContent/"), fileName);
                    file.SaveAs(path);
                    var dataSource = _dataSourceManager.GetById(dataSourceId, Client);
                    var response = _transactionManager.Insert(dataSource, path);
                    HandleResponse(response);
                }
            }
            return RedirectToAction("Index", new {id = dataSourceId});
        }

        protected override void Dispose(bool disposing)
        {
            _transactionManager.Dispose();
            _dataSourceManager.Dispose();
            base.Dispose(disposing);
        }
    }
}

RevenueControl/RevenueControl.Web/Controllers/TransactionsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using RevenueControl.DataAccess;
using RevenueControl.DomainObjects.Entities;
using RevenueControl.DomainObjects.Interfaces;
using RevenueControl.Services;
using RevenueControl.Web.Models;

namespace RevenueControl.Web.Controllers
{
    [Authorize]
    public class TransactionsController : BaseController
    {
        private readonly IDataSourceManager _dataSourceManager = new DataSourceManager(new UnitOfWork());
        private readonly ITransactionManager _transactionManager = new TransactionsManager(new UnitOfWork());

        // GET: Transactions
        public ActionResult Index([Bind(Prefix = "id")] int dataSourceId)
        {
            var dataSource = _dataSourceManager.GetById(dataSourceId, Client);
            IEnumerable<Transaction> transactions = _transactionManager.Get(dataSource);

            var model = new TransactionsViewModel
            {
                DataSource =
                    string.IsNullOrWhiteSpace(dataSource.ClientName)
                        ? dataSource.BankAccount
                        : dataSource.ClientName + " - " + dataSource.BankAccount,
                Transactions = transactions,
                DataSourceId = dataSource.Id
            };

            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            _transactionManager.Dispose();
            base.Dispose(disposing);
        }
    }
}

RevenueControl/RevenueControl.Web/Views/Transactions/Index.cshtml
@model TransactionsViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Transactions for: @Model.DataSource</h2>
@Html.Partial("_Transactions", Model.Transactions)
<p>
    @Html.ActionLink("Upload", "Create")
    @Html.ActionLink("Upload more transactions", "Index", "TransactionUpload", new {id = Model.DataSourceId}, null)
</p>

RevenueControl/RevenueControl.Web/Views/Transactions/_Transactions.cshtml
@model IEnumerable<Transaction>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TransactionDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransactionDetails)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransactionType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OtherDetails)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionDetails)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OtherDetails)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
                @Html.ActionLink("Details", "Details", new {id = item.Id}) |
                @Html.ActionLink("Delete", "Delete", new {id = item.Id})
            </td>
        </tr>
    }

</table>